### ISSUE TITLE
Migration to version 11.0

### ISSUE THREAD

**Issue by adhoc-transbot** [ingadhoc/patches#10]
# Todo

https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-11.0

# Modules to migrate

- [ ] account_partner_reconcile
- [ ] analytic_surveyor
- [ ] auth_brute_force
- [ ] base_name_search_improved
- [ ] base_report_to_printer
- [ ] bi_sql_editor
- [ ] currency_rate_update
- [ ] logos_invoice_analysis
- [ ] logos_product_attributes
- [ ] mass_editing
- [ ] mis_builder
- [ ] purchase_all_shipments
- [ ] purchase_discount
- [ ] sale_exception
- [ ] surveyor
- [ ] surveyor_payments
- [ ] web_m2x_options
- [ ] web_pdf_preview
